services:
  postgres:
    image: postgres:16
    container_name: readytomog-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - readytomog-network
  mongodb:
    image: mongo:6
    container_name: readytomog_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - readytomog_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: readytomog-rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-password}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - readytomog-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  redis:
    container_name: readytomog-redis
    image: redis:6.2
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - readytomog-network
  # postgres-exporter:
  #   container_name: postgres-exporter
  #   image: prometheuscommunity/postgres-exporter
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DATABASE}
  #   ports:
  #     - 9187:9187
  #   networks:
  #     - readytomog-network
  #   depends_on:
  #     - postgres

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter
    restart: always
    command: -redis.addr=redis://:${REDIS_PASSWORD}@redis:6379
    ports:
      - 9121:9121
    networks:
      - readytomog-network
    depends_on:
      - redis

  rabbitmq-exporter:
    container_name: rabbitmq-exporter
    image: kbudde/rabbitmq-exporter
    restart: always
    environment:
      RABBIT_URL: http://readytomog-rabbitmq:15672
      RABBIT_USER: ${RABBIT_USER}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
    ports:
      - 9419:9419
    networks:
      - readytomog-network
    depends_on:
      - rabbitmq
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: always
    ports:
      - 9100:9100
    networks:
      - readytomog-network
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - readytomog-network

volumes:
  postgres-data:
  rabbitmq-data:
  redis_data:

networks:
  readytomog-network:
    driver: bridge
