syntax = "proto3";

package user.v1;

service UserService {
    rpc GetUserById(GetUserByIdRequst) returns (GetUserByIdResponse);
}


message GetUserByIdRequst {
  string userId = 1;
}


enum Role {
  unspecified = 0;
  user = 1;
  participant = 2;
  creator = 3;
  admin = 4;
}

message GetUserByIdResponse{
    string userId = 1;
    string name = 2;
    string surname = 3;
    bool isOtpVerified = 4;
    bool isEmailVerified = 5;
    bool isPhoneVerified = 6;
    bool isTwoFactorEnabled = 7;
    string phone = 8;
    repeated Role roles = 9;
    string email = 10;    
}