server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: auth-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: auth
          service: auth-service
          __path__: /var/log/services/auth/*.log
  - job_name: user-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: user
          service: user-service
          __path__: /var/log/services/user/*.log
  - job_name: chat-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: chat
          service: chat-service
          __path__: /var/log/services/chat/*.log
  - job_name: payment-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: payment
          service: payment-service
          __path__: /var/log/services/payment/*.log
  - job_name: notification-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: notification
          service: notification-service
          __path__: /var/log/services/notification/*.log
